### ISSUE TITLE
During save got this error

### ISSUE THREAD

**Issue by mbhavesh95863** [resilient-tech/bank_integration#1]
Traceback (most recent call last):
  File &quot;/home/frappe/frappe-bench/apps/frappe/frappe/app.py&quot;, line 61, in application
    response = frappe.handler.handle()
  File &quot;/home/frappe/frappe-bench/apps/frappe/frappe/handler.py&quot;, line 21, in handle
    data = execute_cmd(cmd)
  File &quot;/home/frappe/frappe-bench/apps/frappe/frappe/handler.py&quot;, line 56, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File &quot;/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py&quot;, line 1026, in call
    return fn(*args, **newargs)
  File &quot;/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/save.py&quot;, line 22, in savedocs
    doc.save()
  File &quot;/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py&quot;, line 260, in save
    return self._save(*args, **kwargs)
  File &quot;/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py&quot;, line 283, in _save
    self.insert()
  File &quot;/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py&quot;, line 222, in insert
    self.run_before_save_methods()
  File &quot;/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py&quot;, line 876, in run_before_save_methods
    self.run_method(&quot;validate&quot;)
  File &quot;/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py&quot;, line 772, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File &quot;/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py&quot;, line 1048, in composer
    return composed(self, method, *args, **kwargs)
  File &quot;/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py&quot;, line 1031, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File &quot;/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py&quot;, line 766, in &lt;lambda&gt;
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File &quot;/home/frappe/frappe-bench/apps/bank_integration/bank_integration/bank_integration/doctype/bank_integration_settings/bank_integration_settings.py&quot;, line 17, in validate
    bank.login(self.password)
  File &quot;/home/frappe/frappe-bench/apps/bank_integration/bank_integration/bank_integration/api/hdfc_bank_api.py&quot;, line 21, in login
    self.setup_browser()
  File &quot;/home/frappe/frappe-bench/apps/bank_integration/bank_integration/bank_integration/api/bank_api.py&quot;, line 25, in setup_browser
    self.br = webdriver.Chrome(options=options)
  File &quot;/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/selenium/webdriver/chrome/webdriver.py&quot;, line 73, in __init__
    self.service.start()
  File &quot;/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/selenium/webdriver/common/service.py&quot;, line 83, in start
    os.path.basename(self.path), self.start_error_message)
WebDriverException: Message: &apos;chromedriver&apos; executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

**Comment by sagarvora** [comment]
Chromedriver needs to be installed: https://launchpad.net/ubuntu/bionic/+package/chromium-chromedriver
